version: 2

jobs:
  test_7.0:
    working_directory: ~/artisan-view
    docker:
      - image: circleci/php:7.0-cli
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit

  test_7.1:
    working_directory: ~/artisan-view
    docker:
      - image: circleci/php:7.1-cli
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test_7.0
      - test_7.1
