name: Tests (PHP)
on:
    push:
        branches:
            - 'master'
            - 'develop'
        paths:
            - 'src/**'
            - 'tests/**'
            - 'composer.json'
            - 'phpunit.xml.dist'
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'composer.json'
            - 'phpunit.xml.dist'

jobs:
    tests:
        name: PHP ${{ matrix.php }} (${{ matrix.composer_flags }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4]
                composer_flags: ['--prefer-lowest', '--prefer-stable']
        steps:
            - uses: actions/checkout@v1

            - name: Configure PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --no-interaction --no-ansi --no-suggest --prefer-dist ${{ matrix.composer_flags }}

            - name: Execute tests
              run: vendor/bin/phpunit
