name: Tests (PHP)
on:
    push:
    pull_request:

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} (${{ matrix.composer_flags }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4]
                composer_flags: ['--prefer-lowest', '--prefer-stable']
        steps:
            - uses: actions/checkout@v1

            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --no-interaction --no-ansi --no-suggest --prefer-dist ${{ matrix.composer_flags }}

            - name: Execute tests
              run: vendor/bin/phpunit

    phpstan:
        name: PhpStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  extensions: mbstring
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --no-interaction --no-ansi --no-suggest --prefer-dist --prefer-stable

            - name: Run PhpStan
              run: vendor/bin/phpstan analyse src/ tests/ --level=7
